### ISSUE TITLE
大佬能否提供一下服务端代码

### ISSUE THREAD

**Issue by ChenSino** [aixinaxc/mrtcweb#4]
大佬能否提供一下服务端代码

**Comment by aixinaxc** [comment]
ion的新版已经大改，不兼容旧版了。你可以直接学习ion-sfu和ion-sdk-js

**Comment by ChenSino** [comment]
> ion的新版已经大改，不兼容旧版了。你可以直接学习ion-sfu和ion-sdk-js

新版的如何发送自定义事件呢，大佬能否指点一二

**Comment by aixinaxc** [comment]
新版占时不支持自定义事件，社区正在开发ion-biz部分逻辑。这部分到时会包含




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aixinaxc/mrtcweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aixinaxc/mrtcweb] 大佬能否提供一下服务端代码 (#4)





  
ion的新版已经大改，不兼容旧版了。你可以直接学习ion-sfu和ion-sdk-js
  
新版的如何发送自定义事件呢，大佬能否指点一二

**Comment by ChenSino** [comment]
> 新版占时不支持自定义事件，社区正在开发ion-biz部分逻辑。这部分到时会包含
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aixinaxc/mrtcweb" ***@***.***&gt;; 发送时间:&nbsp;2021年3月29日(星期一) 下午2:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [aixinaxc/mrtcweb] 大佬能否提供一下服务端代码 (#4) ion的新版已经大改，不兼容旧版了。你可以直接学习ion-sfu和ion-sdk-js 新版的如何发送自定义事件呢，大佬能否指点一二 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢！
